/**
 * 타입 정의 통합 export
 */

// 기본 타입들
export type {
  ApiResponse,
  ApiError,
  PaginationParams,
  PaginatedResponse,
  BaseComponentProps,
  LoadingState,
  FormField,
  FormState,
  ModalProps,
  ToastProps,
  Theme,
  ThemeContextType,
  SearchResult,
  SearchFilters,
  FileUpload,
  UploadResponse,
  DateRange,
  TimeSlot,
  ChartData,
  StatCard,
  Permission,
  Role,
  UserPermissions,
  AppConfig,
  AppEvent,
  EventHandler,
  CacheItem,
  CacheConfig,
  WebSocketMessage,
  WebSocketConfig,
  ExportOptions,
  ImportResult,
} from './index';

// 도메인별 타입들
export type {
  NewsArticle,
  NewsCategory,
  NewsSource,
  NewsSentiment,
  NewsPriority,
  NewsParams,
  NewsResponse,
  NewsFilters,
  RelatedArticle,
  RelatedArticlesResponse,
  NewsTrend,
  NewsTrendsResponse,
  NewsAnalytics,
  NewsCardProps,
  NewsGridProps,
  NewsFiltersProps,
  NewsSearchProps,
  NewsDetailProps,
  NewsComment,
  NewsCommentsResponse,
  NewsBookmark,
  NewsBookmarksResponse,
  NewsNotification,
  NewsSubscription,
} from './news';

export type {
  User,
  AuthProvider,
  UserRole,
  UserProfile,
  UserPreferences,
  NewsletterFrequency,
  NotificationSettings,
  AuthResponse,
  LoginCredentials,
  RegisterCredentials,
  ResetPasswordRequest,
  ResetPasswordConfirm,
  OAuthCallbackData,
  AdditionalInfo,
  ChangePasswordData,
  UpdateProfileData,
  UpdateAccountData,
  Session,
  AuthState,
  AuthContextType,
  LoginFormProps,
  RegisterFormProps,
  ForgotPasswordFormProps,
  ResetPasswordFormProps,
  OAuthButtonProps,
  AdditionalInfoFormProps,
  ProfileFormProps,
  AccountSettingsProps,
  ChangePasswordFormProps,
  ProtectedRouteProps,
  UsePermissionsReturn,
  UseAuthReturn,
  SocialLoginConfig,
  SecuritySettings,
} from './auth';